baseURL = "http://strykeforce.github.io/"
languageCode = "en-us"
title = "Stryke Force Dev Site"
theme = "nix"

[params]
  GithubID = "strykeforce"
  TwitterID = "2767StrykeForce"
  FacebookID = "2767strykeforce"
  InstagramID = "2767strykeforce"
  Name = "Stryke Force 2767"
  HeaderUsername = "dev"
  HeaderHostname = "strykeforce"
  Email = "jeff@j3ff.io"
  About = "This is the Stryke Force 2767 FRC dev team blog. Stryke Force is a community FIRST robotics team based in Kalamazoo, Michigan."
  ProfilePicture = "strykeforce.jpg"
  GoogleAnalytics = "UA-108186367-2"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/posts"
